import { Document, Paragraph, TextRun, HeadingLevel, Packer } from "docx";

export async function buildDocxBuffer(cvText: string, jobTitle: string, company: string): Promise<Buffer> {
  const lines = cvText.split("\n").filter((l) => l.trim().length > 0);

  const children: Paragraph[] = [];

  for (const line of lines) {
    const trimmed = line.trim();

    if (
      trimmed.toUpperCase() === trimmed &&
      trimmed.length > 2 &&
      trimmed.length < 50 &&
      !trimmed.includes("•") &&
      !trimmed.startsWith("-")
    ) {
      children.push(
        new Paragraph({
          text: trimmed,
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 300, after: 100 },
        }),
      );
    } else if (trimmed.startsWith("•") || trimmed.startsWith("-")) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: trimmed.replace(/^[•\-]\s*/, ""), size: 22 })],
          bullet: { level: 0 },
        }),
      );
    } else {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: trimmed, size: 22 })],
          spacing: { after: 100 },
        }),
      );
    }
  }

  const doc = new Document({
    creator: "ParsePilot AI",
    title: `${jobTitle} - ${company} CV`,
    description: "ATS-optimized CV generated by ParsePilot AI",
    sections: [
      {
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(doc);
  return Buffer.from(buffer);
}
